# Generated by Django 5.1.6 on 2025-02-19 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelprovider',
            name='provider',
            field=models.CharField(default='unknown', max_length=100),
            preserve_default=False,
        ),
    ]
