# Generated by Django 5.1.6 on 2025-02-19 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_fileuploadroutingrule'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegexRoutingPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regex_pattern', models.CharField(max_length=255, unique=True)),
                ('original_model', models.CharField(max_length=100)),
                ('redirect_model', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='RegexRoutingRule',
        ),
    ]
