# Generated by Django 5.1.6 on 2025-02-19 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_regexroutingpolicy_delete_regexroutingrule'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FileUploadRoutingRule',
            new_name='FileRouting',
        ),
        migrations.RenameField(
            model_name='filerouting',
            old_name='model_name',
            new_name='model',
        ),
    ]
