# Generated by Django 5.1.6 on 2025-02-19 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_rename_fileuploadroutingrule_filerouting_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileRoutingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(max_length=20, unique=True)),
                ('provider', models.CharField(max_length=50)),
                ('model_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='FileRouting',
        ),
    ]
