# Generated by Django 5.1.6 on 2025-02-19 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_fileroutingconfig_delete_filerouting'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FileRoutingConfig',
        ),
    ]
