# Generated by Django 5.1.6 on 2025-02-19 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_delete_fileroutingconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileUploadRouting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(max_length=50, unique=True)),
                ('provider', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
            ],
        ),
    ]
